log:
  level: warn

plugins:
  # 缓存
  - tag: "cache"
    type: "cache"
    args:
      size: 10240
      lazy_cache_ttl: 86400

  # 转发给国内 DNS，并发查询
  - tag: "forward_cn"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
        - { tag: alidns, addr: "tls://dns.alidns.com", dial_addr: "223.5.5.5", enable_pipeline: true }
        - { tag: dndpod, addr: "tls://1.12.12.12", enable_pipeline: true }
        - { tag: cfdns, addr: "tls://1.1.1.1", enable_pipeline: true }

  - tag: "forward_fake"
    type: "forward"
    args:
      upstreams:
        - { tag: fakedns, addr: "192.168.6.206:1053" }

  - tag: "direct_domain"
    type: "domain_set"
    args:
      files: ["./apple-cn.txt", "./china-list.txt", "./direct-list.txt", "./direct-tld-list.txt", "./direct-domain.txt"]

  - tag: "reject_domain"
    type: "domain_set"
    args:
      files: ["./reject-list.txt"]

  - tag: "cdn-ddns_domain"
    type: "domain_set"
    args:
      files: ["./cdn-ddns.txt"]

  - tag: "proxy_domain"
    type: "domain_set"
    args:
      files: ["./proxy-domain.txt"]

  - tag: "cn_seq"
    type: "sequence"
    args:
      - { matches: "!qname $cdn-ddns_domain", exec: $cache } # 如果非 cdn 或者 ddns 域名，则查询缓存
      - { matches: [has_resp], exec: accept } # 查找缓存，如果缓存命中，结束
      - { exec: $forward_cn } # 缓存不命中，通过设置的 dot 查询
      # - { exec: query_summary }
      - { exec: accept } # 国内 DNS 查询完成，不再通过 Fake DNS 查询

  - tag: "proxy_seq"
    type: "sequence"
    args:
      - { exec: $forward_fake }
      # - { exec: query_summary }
      - { exec: accept }

  - tag: "main_seq"
    type: "sequence"
    args:
      - { matches: qname $reject_domain, exec: reject 3 }
      - { matches: qname $proxy_domain, exec: goto proxy_seq } # 可以直连，但是希望走代理的域名，例如 bing.com
      - { matches: qname $direct_domain, exec: goto cn_seq } # 匹配到直连域名，则跳转到 cn_sequence
      - { exec: goto proxy_seq } # 没有匹配到直连域名，跳转 proxy_sequence

  - type: "udp_server"
    args: { entry: main_seq, listen: ":5533" }

  - type: "tcp_server"
    args: { entry: main_seq, listen: ":5533" }
