# Profiles Config for Clash Verge

current: lX01j9NzuWaZ
chain: null
valid:
- dns
items:
- uid: rRXVnpmYHfQW
  type: remote
  name: Remote File
  file: rRXVnpmYHfQW.yaml
  url: https://api.v1.mk/sub?target=clash&url=https%3A%2F%2F2324.taosky.com%2F23reality24-sub-dsdadds132d&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_AdblockPlus.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1699106571
  option:
    update_interval: 1440
- uid: liKSG78sFwGq
  type: local
  name: zwy
  file: liKSG78sFwGq.yaml
  desc: meta
  selected:
  - name: PROXY
    now: oracle132kr147-10TB-联通移动电信-韩国
  updated: 1699106870
- uid: lX01j9NzuWaZ
  type: local
  name: Remote File
  file: lX01j9NzuWaZ.yaml
  desc: ''
  updated: 1699113419
