# Profiles Config for Clash Verge

current: riLsjCFysLuT
chain: null
valid:
- dns
items:
- uid: rLAnVitnzgQb
  type: remote
  name: Remote File
  file: rLAnVitnzgQb.yaml
  url: https://sub.id9.cc/sub?target=clash&new_name=true&url=https%3A%2F%2Fhneko.site%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Db82e133f8ff80f8b1053978f89353da9%7Chttps%3A%2F%2Fs1.bnpublicsub.net%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D06fa864e7ad7fb04d055a270579f178d%7Chttps%3A%2F%2Fv2sub.betac1ouds.top%2Fmodules%2Fservers%2FV2raySocks%2FNEWclash.php%3Fsid%3D7197%26token%3Dzj72yNuIbqCx%7Chttps%3A%2F%2Fsub1.smallstrawberry.com%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3De8e6c2e45cf9c1f273a37379c979586a&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full.ini
  extra:
    upload: 338317657
    download: 1929361165
    total: 536870912000
    expire: 1764948155
  updated: 1682046245
  option:
    update_interval: 1440
- uid: rK4uprnDL56h
  type: remote
  name: betacloud
  file: rK4uprnDL56h.yaml
  desc: ''
  url: https://v2sub.betac1ouds.top/modules/servers/V2raySocks/NEWclash.php?sid=7197&token=zj72yNuIbqCx
  selected:
  - name: 节点选择
    now: 日本区1线
  updated: 1682046237
  option:
    with_proxy: false
    self_proxy: false
- uid: rIvnV98e4NTb
  type: remote
  name: Remote File
  file: rIvnV98e4NTb.yaml
  url: https://sub.xeton.dev/sub?target=clash&new_name=true&url=https%3A%2F%2Fhneko.site%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3Db82e133f8ff80f8b1053978f89353da9%7Chttps%3A%2F%2Fs1.bnpublicsub.net%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D06fa864e7ad7fb04d055a270579f178d%7Chttps%3A%2F%2Fv2sub.betac1ouds.top%2Fmodules%2Fservers%2FV2raySocks%2FNEWclash.php%3Fsid%3D7197%26token%3Dzj72yNuIbqCx%7Chttps%3A%2F%2Fsub1.smallstrawberry.com%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3De8e6c2e45cf9c1f273a37379c979586a&insert=false&config=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2FSleepyHeeead%2Fsubconverter-config%40master%2Fremote-config%2Fcustomized%2Fssrcloud.ini
  extra:
    upload: 338317657
    download: 1929361165
    total: 536870912000
    expire: 1764948155
  updated: 1682046240
  option:
    update_interval: 1440
- uid: riLsjCFysLuT
  type: remote
  name: Remote File
  file: riLsjCFysLuT.yaml
  url: https://v1.mk/qCidzuu
  extra:
    upload: 340144727
    download: 1985294937
    total: 536870912000
    expire: 1764948155
  updated: 1682048422
  option:
    update_interval: 1440
- uid: rgAjkw7zyb2x
  type: remote
  name: Remote File
  file: rgAjkw7zyb2x.yaml
  url: https://v1.mk/oeMzkrD
  updated: 1690442498
  option:
    update_interval: 1440
