# Profiles Config for Clash Verge

current: lvibBQPD8cEm
chain: null
valid:
- dns
items:
- uid: lvibBQPD8cEm
  type: local
  name: clmeta
  file: lvibBQPD8cEm.yaml
  desc: lcoalfile
  url: ''
  updated: 1699065107
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 1440
