# Profiles Config for Clash Verge

current: l0NylgJqL5kw
chain: null
valid:
- dns
items:
- uid: l0NylgJqL5kw
  type: local
  name: cv
  file: l0NylgJqL5kw.yaml
  desc: for clash verge
  updated: 1698855041
