# Profiles Config for Clash Verge

current: l7pRXHU5H6C2
chain: null
valid:
- dns
items:
- uid: rRXVnpmYHfQW
  type: remote
  name: Remote File
  file: rRXVnpmYHfQW.yaml
  url: https://api.v1.mk/sub?target=clash&url=https%3A%2F%2F2324.taosky.com%2F23reality24-sub-dsdadds132d&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_AdblockPlus.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true
  updated: 1699359845
  option:
    update_interval: 1440
- uid: l7pRXHU5H6C2
  type: local
  name: meta
  file: l7pRXHU5H6C2.yaml
  desc: ''
  selected:
  - name: PROXY
    now: tao
  updated: 1699439188
