# Profiles Config for Clash Verge

current: rbXslYN4FHzv
chain: null
valid:
  - dns
  - sub-rules
  - unified-delay
items:
  - uid: lrTOb3pAv0Lt
    type: local
    name: verge-tao
    file: lrTOb3pAv0Lt.yaml
    desc: tao and my own node
    updated: 1702368857
