# Profiles Config for Clash Verge

current: rP6aTCpjCFPU
chain: null
valid:
- dns
items:
- uid: rK4uprnDL56h
  type: remote
  name: betacloud
  file: rK4uprnDL56h.yaml
  desc: ''
  url: https://v2sub.betac1ouds.top/modules/servers/V2raySocks/NEWclash.php?sid=7197&token=zj72yNuIbqCx
  selected:
  - name: 节点选择
    now: 日本区1线
  updated: 1682046237
  option:
    with_proxy: false
    self_proxy: false
- uid: rP6aTCpjCFPU
  type: remote
  name: Remote File
  file: rP6aTCpjCFPU.yaml
  url: https://v1.mk/gnhgqyK
  selected:
  - name: 🚀 节点选择
    now: 🇰🇷 韩国节点
  updated: 1691544617
  option:
    update_interval: 1440
